FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
# python3.14 is not in the ubuntu24.04 repos, so pull it from the deadsnakes PPA
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y && apt-get update
RUN apt-get install python3.14 python3-pip -y
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.14 1

# Install opencv-python dependency
RUN apt-get install ffmpeg libsm6 libxext6 -y

# Install poppler for pdf2image (converting pdf to images)
RUN apt-get install poppler-utils -y

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY uv.lock pyproject.toml /app/

COPY docile /app/docile
COPY LICENSE /app/LICENSE
COPY README.md /app/README.md

RUN uv sync --locked --all-extras
