FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install python3.10 python3-pip -y
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

# Install opencv-python dependency
RUN apt-get install ffmpeg libsm6 libxext6 -y

# Install poppler for pdf2image (converting pdf to images)
RUN apt-get install poppler-utils -y

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY uv.lock pyproject.toml /app/

COPY docile /app/docile
COPY LICENSE /app/LICENSE
COPY README.md /app/README.md

RUN uv sync --locked --all-extras
